### ISSUE TITLE
Consider using maven dependency management

### ISSUE THREAD

**Issue by premanandc** [binkley/spring-boot-starter-axon#13]

**Comment by binkley** [comment]
Add description, please.  This isn't Rally.  ;-)

**Comment by premanandc** [comment]
Given that you talk about a multi-module layout, using dependency management is almost mandatory. More here: http://stackoverflow.com/questions/2619598/differences-between-dependencymanagement-and-dependencies-in-maven

**Comment by binkley** [comment]
I know the approach well.  I prefer to keep common dependencies in the parent POM so they are not duplicated in each child POM.

Actually, I guess I did a lot of this anyhow.  :-)  Note how testing deps are gathered together in axon-spring-boot-testing modules, for example.
