### ISSUE TITLE
Consider splitting out query (read side) configuration

### ISSUE THREAD

**Issue by premanandc** [binkley/spring-boot-starter-axon#14]
For a start:
Axon**Command**AutoConfiguration
- AnnotationCommandHandlerBeanPostProcessor
- CommandBus
- CommandGatewayFactoryBean
- Aggregate Repositories

Axon**Query**AutoConfiguratio
- EventBus
- AnnotationEventListenerBeanPostProcessor
- EventStore

**Comment by binkley** [comment]
Why the split?  Don't you always need all of them?

**Comment by premanandc** [comment]
No you don't. The command and query sides are independent, except for the dependency on event definitions. The whole point of CQRS is to enable the command and query sides to remain independent. We haven't done that on the project we work on yet, but we have the benefit of hindsight now.

**Comment by binkley** [comment]
@premanandc  Need to rethink, I may revert this.  Here's why:

The commit breaks out SimpleEventBus, which is only used for single intra-JVM case.  What is needed is separate configuration for distributed event bus, e.g., AMQP or Spring Messaging (JMS).  I already plan for those to be separate modules.

Make sense?
